ostis-ai/sc-machine

sc-kpm/sc-agents-common/utils/AgentUtils.cpp, sc-kpm/sc-agents-common/utils/AgentUtils.hpp, sc-kpm/sc-agents-common/utils/CommonUtils.cpp, sc-kpm/sc-agents-common/utils/CommonUtils.hpp, sc-kpm/sc-agents-common/utils/GenerationUtils.cpp, sc-kpm/sc-agents-common/utils/IteratorUtils.cpp, sc-kpm/sc-agents-common/utils/IteratorUtils.hpp, sc-kpm/sc-agents-common/utils/LogicRuleUtils.cpp, sc-kpm/sc-agents-common/utils/LogicRuleUtils.hpp, sc-kpm/sc-agents-common/utils/SetOperationsUtils.cpp, sc-memory/sc-memory/sc_debug.hpp
- Writing method-replacements for usafe utils methods
- Setting parameters checking in utils method
- Codestyle improvements
=> Utils usability and quality improvements and assertion checks settings

.github/workflows/main.yml, CMakeLists.txt, docs/dev/pr.md
=> Fix build app

README.md, docs/changelog.md, scripts/install_deps_macOS.sh, scripts/install_deps_osx.sh
=> [docs] Update macOS install_deps script

README.md
Unfortunately missed that part in #27, so an additional change is required.
=> [docs]Remove web interface info from README

cmake/FindLibClang.cmake, scripts/install_deps_ubuntu.sh
Trello [card](https://trello.com/c/WuwWrjag).
If in Ubuntu 20.04 run:
```shell
sudo apt install llvm libclang-dev
```
apt will install version 10 of llvm libs, so i decided update llvm version to version 10
=> [build] Update llvm version

CMakeLists.txt, docs/build/cmake-flags.md, sc-memory/tests/CMakeLists.txt, thirdparty/CMakeLists.txt
=> Fix critical CMake issues

.github/workflows/docs.yml, README.md
This PR allows us to publish our docs to GitHub Pages and update the docs automatically
=> Deploy documentation to GitHub Pages

.github/workflows/docs.yml, README.md, docs/index.md, mkdocs.yml
=> Fix mkdocs CI (again...)

config/sc-machine.ini, docs/changelog.md, sc-kpm/CMakeLists.txt, sc-kpm/sc-agents-common/utils/IteratorUtils.cpp, sc-kpm/tests/sc-utils/sc-agents-common-utils.cpp, sc-kpm/tests/tests.cmake
Updates:
- Fix edge types in getAnyByOutRelation utility;
- Add tests module for sc-agents-utils.
Solved issue #37.
=> [tools] Fix edge types in getAnyByOutRelation utility

.gitignore
=> [git] Add debug coverage to gitignore

sc-kpm/sc-agents-common/utils/GenerationUtils.cpp, sc-kpm/tests/sc-utils/sc-agents-common-utils.cpp
=> [tools] Fix basic sequence in wrapInOrientedSetBySequenceRelation utility

docs/changelog.md, sc-memory/sc-memory/utils/sc_log.hpp
This PR depends on PR #56 and carry throught unique style for commands writing.
Notice: This PR can crush another applied ostis-projects, so if there are problems, it takes effort to fix them.
=> [refactor] Fix logging messages utils

docs/changelog.md, scripts/kb_scripts/support_scripts/scs_writer.py
=> [tools][build] Add opportunity to parse russian identifiers in gwf2scs-translator

docs/changelog.md, docs/storage/sc-dictionary.md, sc-memory/sc-core/sc-store/sc-container/sc-dictionary/sc_dictionary.c, sc-memory/sc-core/sc-store/sc-container/sc-dictionary/sc_dictionary.h, sc-memory/sc-core/sc-store/sc-fs-storage/sc_dictionary_fs_storage.c, sc-memory/sc-core/sc-store/sc-fs-storage/sc_dictionary_fs_storage.h, sc-memory/sc-core/sc-store/sc-fs-storage/sc_fs_storage.c, sc-memory/sc-core/sc-store/sc-fs-storage/sc_fs_storage.h, sc-memory/sc-core/sc-store/sc-fs-storage/sc_fs_storage_builder.h, sc-memory/sc-core/sc-store/sc-fs-storage/sc_rocksdb_fs_storage.cpp, sc-memory/sc-core/sc-store/sc-fs-storage/sc_rocksdb_fs_storage.h, sc-memory/sc-core/sc-store/sc_storage.c, sc-memory/sc-core/sc-store/sc_storage.h, sc-memory/sc-core/sc_memory.c, sc-memory/sc-core/sc_memory.h, sc-memory/sc-memory/sc_memory.cpp, sc-memory/sc-memory/sc_memory.hpp, sc-memory/tests/sc-memory/common/sc-link.cpp, sc-memory/tests/sc-memory/containers/sc-dictionary.cpp
=> [memory][sc-fs-storage][sc-dictionary][sc-rocksdb] Add opportunity to search links by substring

docs/changelog.md, sc-memory/sc-memory/sc_memory.hpp, sc-memory/tests/sc-memory/common/sc-memory.cpp
=> Add sc-memory string API for set and get link content methods

sc-kpm/sc-ui/translators/uiTranslatorFromSc.cpp
=> [tools][fix] Use base hash function for addrs

sc-memory/sc-core/sc-store/sc-container/sc-dictionary/sc_dictionary.c, sc-memory/sc-core/sc-store/sc-container/sc-string/sc_string.h, sc-memory/sc-core/sc-store/sc-fs-storage/sc_dictionary_fs_storage.c, sc-memory/sc-core/sc-store/sc_storage.c
=> [memory][sc-fs-storage][sc-dictionary] Fix memory leak, add prefix removing in sc-dictionary destroy

.devcontainer/devcontainer.json, .dockerignore, .github/workflows/main.yml, .github/workflows/release.yml, Dockerfile, README.md, dependencies.cmake, docs/build/linux-build.md, docs/build/osx-build.md, docs/changelog.md, docs/dev/devcontainer.md, docs/docker.md, docs/other/repofile.md, mkdocs.yml, scripts/install_deps_ubuntu.sh, scripts/make_all.sh
=> Dockerize sc-machine

codecov.yml, docs/changelog.md
=> [ci] Up codecov target from 40% to 60%

README.md, docs/changelog.md, mkdocs.yml
=> Write sc-machine idea in readme

CMakeLists.txt, sc-memory/sc-memory/sc_memory.cpp, sc-memory/sc-memory/sc_memory.hpp, sc-tools/sc-builder/src/main.cpp, scripts/build_kb.py, scripts/install_deps_ubuntu.sh
=> 0.7.0 detach bin

CMakeLists.txt, docs/build/linux-build.md, docs/build/osx-build.md, docs/changelog.md, docs/sc-tools/kb_builder.md, sc-memory/sc-memory/sc_memory.cpp, sc-memory/sc-memory/sc_memory.hpp, sc-tools/sc-builder/src/main.cpp, scripts/build_kb.py, scripts/install_deps_ubuntu.sh
=> Hotfixes for prerelease 0.7.0

sc-kpm/sc-search/search.c, sc-kpm/tests/sc-agents/sc-core-agents.cpp
=> [kpm] Change max access rights in sc-search context to min

README.md, docs/changelog.md, docs/sc-network/sc_json.g4, requirements.txt, sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-action/sc_memory_handle_link_content_json_action.hpp, sc-tools/sc-server/src/sc-server-impl/sc_server.hpp, sc-tools/sc-server/src/sc-server-impl/sc_server_defines.hpp, sc-tools/sc-server/src/sc-server-impl/sc_server_impl.hpp, sc-tools/sc-server/src/sc-server-impl/sc_server_message_action.hpp, scripts/healthcheck.py
Usage example:
- run `sc-server.sh`
- install wscat tool `sudo npm install -g wscat`
- complete `wscat -c ws://localhost:8090 -x "{\"type\": \"healthcheck\"}"`
- answer must be `OK` when server is alive, else must be `NO`
=> [tools] Add sc-server healthcheck

docs/changelog.md, sc-memory/sc-memory/sc_scs_helper.cpp, sc-memory/sc-memory/sc_scs_helper.hpp, sc-tools/sc-server/src/main.cpp, sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-action/sc_memory_check_elements_json_action.hpp, sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-action/sc_memory_create_elements_by_scs_json_action.hpp, sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-action/sc_memory_create_elements_json_action.hpp, sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-action/sc_memory_delete_elements_json_action.hpp, sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-action/sc_memory_handle_keynodes_json_action.hpp, sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-action/sc_memory_handle_link_content_json_action.hpp, sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-action/sc_memory_json_action.hpp, sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-action/sc_memory_json_actions_handler.cpp, sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-action/sc_memory_json_actions_handler.hpp, sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-action/sc_memory_template_generate_json_action.hpp, sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-action/sc_memory_template_search_json_action.hpp, sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-event/sc_memory_json_events_handler.cpp, sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-event/sc_memory_json_events_handler.hpp, sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-event/sc_memory_json_events_manager.hpp, sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc_memory_json_handler.cpp, sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc_memory_json_handler.hpp, sc-tools/sc-server/src/sc-server-impl/sc_server.hpp, sc-tools/sc-server/src/sc-server-impl/sc_server_action.hpp, sc-tools/sc-server/src/sc-server-impl/sc_server_impl.cpp, sc-tools/sc-server/src/sc-server-impl/sc_server_impl.hpp, sc-tools/sc-server/src/sc-server-impl/sc_server_message_action.hpp, sc-tools/sc-server/tests/api/units/sc_server_test.hpp, sc-tools/sc-server/tests/api/units/test_base.cpp, sc-tools/sc-server/tests/sc_client.hpp
=> [tools][sc-server] Change error flow, add errors check for json

docs/changelog.md, sc-memory/sc-memory/sc_wait.hpp, sc-memory/tests/sc-memory/events/sc-wait.cpp
=> Add ability to pass a function for action initiation before waiting for it to finish

sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-event/sc_memory_json_events_handler.cpp, sc-tools/sc-server/src/sc-server-impl/sc_server_message_action.hpp, sc-tools/sc-server/tests/api/units/test_base.cpp, sc-tools/sc-server/tests/api/units/test_connection.cpp, scripts/healthcheck.py
=> FIx event and status value in sc-server event handler

scripts/healthcheck.py
=> fix: sc-server healthcheck

docs/changelog.md, sc-kpm/sc-agents-common/utils/AgentUtils.cpp, sc-kpm/sc-agents-common/utils/AgentUtils.hpp, sc-kpm/tests/sc-utils/sc-agents-common-utils.cpp, sc-kpm/tests/test-agents/FinishActionTestAgent.cpp, sc-kpm/tests/test-agents/FinishActionTestAgent.hpp, sc-kpm/tests/tests.cmake
=> [kpm] Update agent utils with new logic for action initiation

docs/changelog.md, sc-memory/sc-core/sc-store/sc-container/sc-dictionary/sc_dictionary.h, sc-memory/sc-core/sc-store/sc_stream_memory.c, sc-memory/sc-memory/utils/sc_exec.hpp, sc-tools/sc-builder/src/scs_translator.cpp, sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-action/sc_memory_handle_link_content_json_action.hpp
=> [server][builder] Convert binary to base64 format in build step

.github/workflows/main.yml, cmake/FindLibClang.cmake, docs/build/osx-build.md, docs/changelog.md, sc-memory/sc-core/sc-store/sc-fs-storage/sc_dictionary_fs_storage.c, sc-memory/sc-core/sc-store/sc-fs-storage/sc_file_system.c, sc-memory/sc-core/sc-store/sc-fs-storage/sc_file_system.h, sc-memory/sc-core/sc-store/sc-fs-storage/sc_fs_storage.c, sc-memory/sc-core/sc-store/sc-fs-storage/sc_rocksdb_fs_storage.cpp, sc-memory/sc-core/sc-store/sc_event.c, sc-memory/sc-core/sc-store/sc_link_helpers.c, sc-memory/sc-core/sc-store/sc_segment.c, sc-memory/sc-memory/utils/sc_lock.cpp, sc-tools/sc-config-utils/sc-config/sc_config.hpp, sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-action/sc_memory_make_template_json_action.hpp, scripts/install_deps_macOS.sh
- Fix glib cats for ubuntu 22.04 and masOS
- Fix rocksdb for ubuntu 22.04
- Add ci for ubuntu 22.04 and macOS
- Fix llvm and clang linking for macOS
=> [ci] Fix glib casts and add ci for ubuntu 22.04 and macOS

sc-memory/sc-core/sc-store/sc-fs-storage/sc_fs_storage.c
=> [memory][fix] Create directory for binaries if doesn't exist

.github/workflows/docker.yml, .github/workflows/main.yml, docker-compose.yml, sc-tools/sc-server/src/main.cpp, scripts/docker_entrypoint.sh, scripts/healthcheck.py
=> [ci] Add ci for docker run on ubuntu-latest

.gitignore, README.md, docker-compose.yml, docs/docker.md, mkdocs.yml, scripts/docker_entrypoint.sh
Planned: additional gif files or illustrations demonstrating:
- the KG-building and agent-based processing mechanisms (will replace the "sc-machine contains" section)
- Full usage example (with data operations visualised separately) - the demo section will be added: 
1. writing a new source file
2. launching the system
3. calling a processing agent 
4. getting a response
=> Revamp README.md

sc-memory/sc-core/sc-store/sc-fs-storage/sc_dictionary_fs_storage.c, sc-memory/sc-core/sc-store/sc-fs-storage/sc_dictionary_fs_storage.h, sc-memory/sc-core/sc-store/sc-fs-storage/sc_fs_storage.c, sc-memory/sc-core/sc-store/sc-fs-storage/sc_fs_storage.h, sc-memory/sc-core/sc-store/sc-fs-storage/sc_rocksdb_fs_storage.cpp, sc-memory/sc-core/sc-store/sc-fs-storage/sc_rocksdb_fs_storage.h, sc-memory/sc-core/sc-store/sc_storage.c, sc-memory/sc-core/sc-store/sc_storage.h, sc-memory/sc-core/sc_memory.c, sc-memory/sc-core/sc_memory.h, sc-memory/sc-memory/sc_memory.cpp, sc-memory/sc-memory/sc_memory.hpp, sc-memory/tests/sc-memory/common/sc-link.cpp, sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-action/sc_memory_handle_link_content_json_action.hpp
=> [memory][fs-storage] Search by substring as prefix if length < 4

README.md, docs/build/osx-build.md, scripts/install_deps_macOS.sh
=> fix macOS and Docker instructions

.github/workflows/release.yml
=> [ci] Fix Docker push tags

.github/workflows/release.yml
=> [ci] Remove linux arm v7 target platform

docs/changelog.md, sc-memory/sc-memory/sc_template_search.cpp, sc-memory/sc-memory/utils/sc_console.hpp, sc-memory/tests/sc-memory/_test/sc_test.hpp, sc-tools/sc-builder/tests/kb/test_templates/template_1.scs, sc-tools/sc-builder/tests/kb/test_templates/template_2.scs, sc-tools/sc-builder/tests/kb/test_templates/test_template_1.gwf, sc-tools/sc-builder/tests/units/test_base.cpp, sc-tools/sc-builder/tests/units/test_defines.hpp
=> [memory][search] Fix dependence order in all var triples

docs/changelog.md, sc-memory/sc-core/sc-store/sc-container/sc-dictionary/sc_dictionary.c, sc-memory/sc-core/sc-store/sc-fs-storage/sc_dictionary_fs_storage.c, sc-memory/sc-core/sc_helper.c, sc-memory/tests/sc-memory/containers/sc-dictionary.cpp
Fix https://github.com/ostis-ai/sc-machine/issues/192
=> [memory][fs-storage] Fix dictionary strings merging

docs/changelog.md, sc-memory/sc-memory/sc_scs_helper.cpp, sc-memory/sc-memory/sc_scs_helper.hpp, sc-memory/tests/sc-memory/scs/scs-helper.cpp
Append generated elements by `SCs-helper` into requested output structure
=> [memory][scs-helper] Append generated elements to output structure if it exists

docs/changelog.md, docs/storage/sc-dictionary.md, sc-memory/sc-core/sc-store/sc-container/sc-dictionary/sc_dictionary.c, sc-memory/sc-core/sc-store/sc-container/sc-dictionary/sc_dictionary.h, sc-memory/sc-core/sc-store/sc-container/sc-list/sc_list.c, sc-memory/sc-core/sc-store/sc-fs-storage/sc_dictionary_fs_storage.c, sc-memory/sc-core/sc-store/sc-fs-storage/sc_rocksdb_fs_storage.cpp, sc-memory/sc-core/sc-store/sc_storage.c, sc-memory/tests/sc-memory/common/sc-link.cpp, sc-memory/tests/sc-memory/containers/sc-dictionary.cpp, sc-tools/sc-builder/tests/units/test_defines.hpp
=> [memory][fs-storage] Fix link deletion and empty link content handling

.github/PULL_REQUEST_TEMPLATE.md
=> [git] Change pr documentation link in pr template

docs/changelog.md, sc-memory/sc-memory/scs/scs.g4, sc-memory/sc-memory/scs/scs_parser.cpp, sc-memory/sc-memory/scs/scs_parser.hpp, sc-memory/tests/sc-memory/scs/scs-helper.cpp
Changes:
- `SCs-parser` create structure twice
- `SCs-parser` doesn't unite all generated elements into structure
Fixed https://github.com/ostis-ai/sc-machine/issues/205
=> [memory][scs-parser] Fix structures begins and ends handling

docs/changelog.md, sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc_memory_json_handler.cpp, sc-tools/sc-server/src/sc-server-impl/sc_server_message_action.hpp, sc-tools/sc-server/tests/api/units/test_base.cpp
Fixed https://github.com/ostis-ai/sc-machine/issues/190
=> [tools][sc-server] Fix no json string request messages parsing

docs/changelog.md, sc-memory/sc-core/sc_helper.c, sc-memory/sc-core/sc_helper.h, sc-memory/tests/sc-memory/common/sc-memory.cpp
=> [test] Add test to resolve node with russian idtf

.gitignore, .gitmodules, README.md, docs/build/linux-build.md, docs/build/osx-build.md, docs/changelog.md, docs/main.tex
=> Add main docs file

docs/changelog.md, sc-memory/sc-memory/sc_wait.hpp
=> [memory] Remove 1 minute assert in wait method for ScWait

sc-tools/sc-config-utils/sc_memory_config.hpp
=> [config] Revert clear flag behaviour

config/sc-machine.ini, docs/changelog.md, sc-memory/sc-core/sc_memory.c, sc-memory/sc-core/sc_memory_params.c, sc-memory/sc-core/sc_memory_params.h, sc-memory/sc-memory/sc_keynodes.cpp, sc-memory/sc-memory/sc_keynodes.hpp, sc-memory/sc-memory/sc_memory.cpp, sc-memory/tests/sc-memory/_test/sc_test.hpp, sc-memory/tests/sc-memory/common/sc-memory.cpp, sc-tools/sc-builder/src/main.cpp, sc-tools/sc-config-utils/sc_memory_config.hpp
Adding init keynodes to result struct and tests for this
=> Add init keynodes to result structure

docs/changelog.md, sc-memory/sc-core/sc_helper.c, sc-memory/sc-core/sc_helper.h, sc-memory/sc-memory/sc_memory.cpp, sc-memory/sc-memory/sc_memory.hpp, sc-memory/sc-memory/sc_scs_helper.cpp, sc-memory/tests/sc-memory/common/sc-memory-api.cpp, sc-memory/tests/sc-memory/scs/scs-helper.cpp
Fixed https://github.com/ostis-ai/sc-machine/issues/207
=> [memory][scs-helper] Add system identifiers to output structure

docs/changelog.md, sc-memory/sc-memory/sc_scs_helper.cpp, sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-action/sc_memory_create_elements_by_scs_json_action.hpp, sc-tools/sc-server/tests/api/units/test_base.cpp
Depends on https://github.com/ostis-ai/sc-machine/pull/211 and https://github.com/ostis-ai/sc-machine/pull/222
=> [tools][server] Add output structure to sc-server create elements by SCs endpoint

sc-memory/sc-memory/scs/scs_parser.cpp, sc-memory/tests/sc-memory/scs/scs-helper.cpp
=> [memory][scs] Fix contour with join type

sc-tools/sc-builder/src/builder.cpp, sc-tools/sc-builder/src/builder.hpp, sc-tools/sc-builder/tests/units/test_base.cpp
=> [builder] Add output structure identifier fiver into itself

docs/changelog.md, sc-memory/sc-memory/sc_type.cpp, sc-memory/sc-memory/sc_type.hpp, sc-memory/sc-memory/scs/scs.g4, sc-memory/sc-memory/scs/scs_parser.cpp, sc-memory/sc-memory/scs/scs_parser.hpp, sc-memory/sc-memory/scs/scs_types.cpp, sc-memory/tests/scs/units/test_scs_common.cpp
=> [sc-memory][tests][changelog] Edit scs parser according to standart

docs/changelog.md, sc-memory/sc-core/sc-store/sc-fs-storage/sc_dictionary_fs_storage.c
Fix https://github.com/ostis-ai/ostis-web-platform/issues/45
=> [memory][fs-storage] Fix hashes size

.pre-commit-config.yaml, docs/changelog.md
=> [ci] Update pre-commit config

sc-memory/sc-memory/sc_addr.hpp
=> [memory][refactor] Fix typo in ScAddrLessFunc

docs/changelog.md, scripts/kb_scripts/remove_scsi.py
=> [scripts] Update remove_scsi preprocess

sc-memory/sc-core/sc_helper.c
=> [memory][helper] Free regex

docs/changelog.md, sc-tools/sc-server/tests/api/units/test_connection.cpp, sc-tools/sc-server/tests/sc_client.hpp
=> [tests][tools] Remove pointer for sc-client core

docs/changelog.md, sc-memory/sc-core/sc-store/sc-fs-storage/sc_dictionary_fs_storage.c, sc-memory/sc-core/sc-store/sc_storage.h, sc-tools/sc-server/src/sc-server-impl/sc_server.hpp, sc-tools/sc-server/tests/api/units/test_connection.cpp, sc-tools/sc-server/tests/sc-server-test.ini
=> [tools][memory] Lookup save and update memory state

docs/changelog.md, sc-tools/sc-builder/src/scs_loader.cpp, sc-tools/sc-builder/src/scs_loader.hpp
=> [tools][builder] Add return value for loader

sc-tools/CMakeLists.txt, scripts/make_all.sh
Add flag for build sc-machine with sc-component-manager support.
Need to merge #259 first.
=> [cmake][scripts] Add component manager flag

docs/changelog.md, scripts/run_sc_component_manager.sh
=> [scripts] Add run script for sc-component manager

docs/changelog.md, sc-kpm/sc-agents-common/utils/IteratorUtils.cpp, sc-kpm/tests/sc-utils/sc-agents-common-iterator-utils.cpp, sc-kpm/tests/sc-utils/sc-agents-common-utils.cpp
=> Refactor get next from set util

sc-kpm/tests/sc-agents/sc-threaded-core-agents.cpp, sc-memory/sc-core/sc-store/sc_event.c, sc-memory/sc-core/sc-store/sc_event/sc_event_private.h, sc-memory/sc-core/sc-store/sc_event/sc_event_queue.c, sc-memory/sc-core/sc-store/sc_event/sc_event_queue.h, sc-memory/sc-core/sc_memory_params.c, sc-memory/sc-core/sc_memory_params.h, sc-memory/tests/sc-memory/_test/sc_test.hpp, sc-memory/tests/sc-memory/tests.cmake, sc-tools/sc-config-utils/sc_memory_config.hpp
=> [tests] Divide ScMemoryTest and ScSingleThreadedMemoryTest

scripts/docker_entrypoint.sh
Fix https://github.com/ostis-ai/sc-machine/issues/267
=> [scripts] Fix docker_entrypoint.sh

sc-kpm/sc-agents-common/utils/GenerationUtils.cpp, sc-kpm/sc-agents-common/utils/IteratorUtils.cpp, sc-memory/sc-memory/sc_debug.hpp, sc-memory/sc-memory/scs/scs_parser.cpp, sc-memory/sc-memory/utils/sc_log.cpp, sc-tools/codegen/Parser/Main.cpp, sc-tools/codegen/Parser/ReflectionParser.cpp, thirdparty/antlr/runtime/src/NoViableAltException.cpp, thirdparty/antlr/runtime/src/atn/ATNState.h
=> [refactor] Illuminate warnings

scripts/build_kb.py, scripts/run_sc_component_manager.sh
=> [scripts] Update scripts for component manager

.github/workflows/main.yml, .gitignore, Dockerfile, README.md, docker-compose.yml, docs/changelog.md, docs/docker.md, sc-machine.ini, scripts/build_kb.py, scripts/install_deps_macOS.sh
Those are mostly small quality of life improvements I would like to become a part of 0.8.0
=> [docker] Usability enhancements

docs/dev/codestyle.md
=> [doc] Update codestyle doc

scripts/run_sc_component_manager.sh
=> [scripts][git] Fix run component manager script, update submodule version

docs/changelog.md, sc-memory/sc-memory/sc_struct.cpp, sc-memory/sc-memory/sc_struct.hpp, sc-memory/sc-memory/sc_template.cpp, sc-memory/sc-memory/sc_template.hpp, sc-memory/sc-memory/sc_template_build.cpp, sc-memory/sc-memory/sc_template_gen.cpp, sc-memory/sc-memory/sc_template_scs.cpp, sc-memory/sc-memory/sc_template_search.cpp, sc-memory/tests/sc-memory/common/sc-elements.cpp, sc-memory/tests/sc-memory/templates/sc-templates-api.cpp, sc-memory/tests/sc-memory/templates/sc-templates-build.cpp, sc-memory/tests/sc-memory/templates/sc-templates-gen-api.cpp, sc-memory/tests/sc-memory/templates/sc-templates-search.cpp, sc-tools/sc-builder/tests/kb/test_templates/template_2.scs, sc-tools/sc-builder/tests/units/test_base.cpp, sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-action/sc_memory_template_generate_json_action.hpp, sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-action/sc_memory_template_search_json_action.hpp
=> [memory][template][build] Not use system identifiers in sc-template-build

sc-memory/sc-memory/sc_struct.cpp, sc-memory/sc-memory/sc_template.hpp, sc-memory/sc-memory/sc_template_gen.cpp, sc-memory/sc-memory/sc_template_search.cpp
=> [memory][template][revert] Allow template search and gen results copying

sc-memory/sc-memory/sc_template.cpp, sc-memory/sc-memory/sc_template.hpp, sc-tools/sc-builder/tests/units/test_base.cpp
=> [memory][template] Get replacements with var idtfs keys

docs/changelog.md, sc-memory/sc-core/sc_helper.c
=> [memory][helper] Return empty sc_addr if not found by idtf

sc-tools/sc-builder/src/builder.cpp, sc-tools/sc-config-utils/sc_builder_config.hpp, sc-tools/sc-config-utils/sc_memory_config.hpp
=> [tools][config] Fix repeated params parsing

sc-memory/sc-memory/sc_template.cpp, sc-memory/sc-memory/sc_template.hpp, sc-memory/sc-memory/sc_template_search.cpp, sc-memory/tests/sc-memory/templates/sc-templates-search-api.cpp
=> [memory][template-search] Optimize search for one-tripled templates

docs/changelog.md, sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-action/sc_memory_delete_elements_json_action.hpp, sc-tools/sc-server/tests/api/units/test_base.cpp, sc-tools/sc-server/tests/api/units/test_connection.cpp
=> [tools][sc-server] Revert erase endpoint

sc-memory/sc-core/sc-store/sc-fs-memory/sc_fs_memory.c, sc-memory/sc-core/sc-store/sc-fs-memory/sc_fs_memory.h, sc-memory/sc-core/sc-store/sc_event/sc_event_queue.c, sc-memory/sc-core/sc_helper.c, sc-memory/sc-core/sc_memory.c, sc-tools/sc-builder/src/main.cpp, sc-tools/sc-config-utils/sc-config/sc_config.cpp, sc-tools/sc-config-utils/sc_memory_config.hpp, sc-tools/sc-server/src/main.cpp, sc-tools/sc-server/src/sc-server-impl/sc_server.hpp, sc-tools/sc-server/src/sc_server_factory.cpp, sc-tools/sc-server/tests/api/units/test_connection.cpp
=> [tools][sc-server][memory] Fix sc-server options and config order

sc-memory/sc-core/sc-store/sc-fs-memory/sc_dictionary_fs_memory.c, sc-memory/sc-core/sc-store/sc-fs-memory/sc_file_system.c, sc-memory/sc-core/sc-store/sc-fs-memory/sc_file_system.h, sc-memory/sc-core/sc-store/sc-fs-memory/sc_fs_memory.c, sc-memory/tests/sc-memory/fs-storage/sc-dictionary-fs-memory-api.cpp
=> [memory][fs-memory] Opportunity to clear on initialize

scripts/build_sc_machine.sh, scripts/formats.sh, scripts/make_all.sh, scripts/run_tests.sh, scripts/set_vars.sh
=> [scripts] Separate build and sc-machine paths

docs/changelog.md
=> [docs] Stylize and make more clear changelog

Dockerfile
=> [docker] Build in release mode

docs/changelog.md, docs/cpp/common.md, sc-memory/sc-memory/kpm/sc_agent.cpp, sc-memory/sc-memory/sc_debug.hpp, sc-memory/sc-memory/sc_event.cpp, sc-memory/sc-memory/sc_memory.cpp, sc-memory/sc-memory/sc_memory.hpp, sc-memory/sc-memory/sc_scs_helper.cpp, sc-memory/sc-memory/sc_stream.cpp, sc-memory/sc-memory/sc_utils.hpp, sc-memory/sc-memory/scs/scs.g4, sc-memory/sc-memory/scs/scs_parser.cpp, sc-memory/sc-memory/scs/scs_types.cpp, sc-memory/tests/performance/units/template_search_complex.hpp, sc-memory/tests/sc-memory/common/sc-memory-api.cpp, sc-memory/tests/sc-memory/fs-storage/sc-dictionary-fs-memory-api.cpp, sc-tools/codegen/Parser/LanguageTypes/Class.cpp, sc-tools/sc-builder/src/builder.cpp, sc-tools/sc-server/src/sc-server-impl/sc_server.cpp
=> [memory] Check types in sc-elements creation methods, remove asserts

.github/workflows/main.yml, Dockerfile, docs/changelog.md, sc-tools/codegen/Parser/LanguageTypes/Class.cpp, scripts/build_sc_machine.sh, scripts/docker_entrypoint.sh, scripts/install_dependencies.sh, scripts/install_deps_macOS.sh, scripts/install_deps_python.sh, scripts/install_deps_ubuntu.sh
=> hotfixes: before release 0.8.0

docs/changelog.md, sc-memory/sc-memory/sc_template.hpp, sc-memory/tests/sc-memory/templates/sc-template-params-api.cpp, sc-tools/sc-builder/tests/units/test_base.cpp
=> [memory][template][params] Add and get addresses by variable addresses

scripts/install_sc_component_manager_dependencies.sh
Need for https://github.com/ostis-ai/ostis-web-platform/pull/85/files/8f78b43e00ca6a29165001720d21ba396a9bc280#diff-76b39a5d7fe4d7525fed88801cdcfb995acb45bbfa56712847c9de0222aeede5
=> [scripts] Add install_sc_component_manager_dependencies script

CMakeLists.txt, docs/changelog.md
=> [docs] Release 0.8.0

docs/changelog.md, sc-memory/sc-memory/scs/scs.g4
=> [memory][scs] Fix internal sentences after sc.s-contours assignments

docs/changelog.md, sc-kpm/sc-agents-common/utils/AgentUtils.cpp
=> [kpm] Reorder agent finish edges creation

scripts/build_sc_machine.sh
=> [scripts] Fix path to binaries

scripts/run_sc_component_manager.sh
This script was ignoring interactive mode flag
=> [scripts] Fix run_sc_component_manager flags

docs/changelog.md, sc-memory/sc-core/sc-store/sc_iterator3.c, sc-memory/sc-core/sc-store/sc_iterator5.c, sc-memory/sc-core/sc-store/sc_storage.c, sc-memory/sc-core/sc-store/sc_types.h, sc-memory/sc-memory/sc_iterator.hpp, sc-memory/tests/sc-memory/common/sc-elements.cpp, sc-memory/tests/sc-memory/common/sc-iterator3.cpp, sc-memory/tests/sc-memory/common/sc-memory.cpp, sc-memory/tests/sc-memory/events/sc-event.cpp, sc-memory/tests/sc-memory/templates/sc-templates-common.cpp
=> [memory][storage] Fix searching sc-edges

docs/changelog.md, scripts/kb_scripts/support_scripts/scs_writer.py
=> [scripts][gwf2scs] Fix parse contours identifiers

docs/changelog.md, sc-tools/sc-builder/src/gwf_translator.cpp, scripts/kb_scripts/gwf_to_scs.py
=> [builder][scripts][gwf2scs] Fix deleting existing and translated .scs sources with the same name

sc-kpm/sc-agents-common/keynodes/coreKeynodes.cpp, sc-kpm/sc-agents-common/keynodes/coreKeynodes.hpp
=> [kpm] Add coreKeynode of nrel_system_identifier

docs/changelog.md, sc-kpm/sc-utils/utils_erase_elements.c
=> [kpm] Fix agent_erase_elements behavior on not his actions

sc-memory/sc-core/sc-store/sc_storage.c
=> [memory] Hotfixes for getting not engaged and released segments

sc-memory/sc-core/sc-store/sc_element.h, sc-memory/sc-core/sc-store/sc_iterator3.c, sc-memory/sc-core/sc-store/sc_storage.c, sc-memory/sc-core/sc_memory.c, sc-memory/tests/sc-memory/common/sc-elements.cpp
=> [memory] Hotfixes of arcs deletion due edge creation

.github/workflows/coverage.yml, codecov.yml
=> [ci][codecov] Update codecov yaml settings

docs/changelog.md, sc-memory/sc-core/sc-store/sc_iterator5.c, sc-memory/sc-core/sc-store/sc_iterator5.h, sc-memory/sc-memory/sc_iterator.cpp, sc-memory/tests/sc-memory/common/sc-iterator-core.cpp, sc-memory/tests/sc-memory/common/sc-iterator5.cpp
=> [memory][iterator][tests] Implement iterator5 AAAAF

sc-memory/sc-core/sc-store/sc-fs-memory/sc_dictionary_fs_memory.c, sc-memory/tests/sc-memory/common/sc-elements.cpp, sc-memory/tests/sc-memory/common/sc-memory.cpp
=> [memory] Fix sync deleting link with empty content

docs/changelog.md, sc-memory/sc-memory/sc_template.cpp, sc-memory/sc-memory/sc_template.hpp, sc-memory/sc-memory/sc_template_build.cpp, sc-tools/sc-builder/tests/units/test_base.cpp
=> [api] Add hashes handling for params

docs/changelog.md, sc-memory/sc-memory/scs/scs.g4, sc-memory/tests/scs/units/test_scs_level_1.cpp, sc-tools/sc-builder/tests/kb/contents.scs, sc-tools/sc-builder/tests/units/test_contents.cpp
=> [memory][scs] Support sc-links for SCs-code level 1

docs/changelog.md, sc-memory/sc-memory/scs/scs.g4, sc-memory/tests/scs/units/test_scs_level_2.cpp
=> [memory][scs] Support recursive curl braces for SCs-code level 2

docs/build/config.md, docs/changelog.md, sc-machine.ini, sc-memory/sc-core/sc-store/sc-event/sc_event_queue.c, sc-memory/sc-core/sc-store/sc-event/sc_event_queue.h, sc-memory/sc-core/sc-store/sc-fs-memory/sc_fs_memory.c, sc-memory/sc-core/sc-store/sc_storage.c, sc-memory/sc-core/sc-store/sc_storage.h, sc-memory/sc-core/sc-store/sc_storage_dump_manager.c, sc-memory/sc-core/sc-store/sc_storage_dump_manager.h, sc-memory/sc-core/sc-store/sc_storage_private.h, sc-memory/sc-core/sc_memory_params.c, sc-memory/sc-core/sc_memory_params.h, sc-memory/tests/sc-memory/_test/sc_test.hpp, sc-memory/tests/sc-memory/common/test_sc_elements.cpp, sc-tools/sc-builder/src/main.cpp, sc-tools/sc-builder/tests/units/builder_test.hpp, sc-tools/sc-builder/tests/units/sc-builder-test.ini, sc-tools/sc-builder/tests/units/test_config.cpp, sc-tools/sc-config-utils/sc_memory_config.hpp, sc-tools/sc-server/CMakeLists.txt, sc-tools/sc-server/src/sc-server-impl/sc_server.cpp, sc-tools/sc-server/src/sc-server-impl/sc_server.hpp, sc-tools/sc-server/src/sc-server-impl/sc_server_impl.cpp, sc-tools/sc-server/src/sc-server-impl/sc_server_impl.hpp, sc-tools/sc-server/src/sc_server_factory.cpp, sc-tools/sc-server/tests/api/units/sc_server_test.hpp, sc-tools/sc-server/tests/api/units/test_connection.cpp, sc-tools/sc-server/tests/sc-server-test.ini
=> [memory][config] Implement config options for disabling sc-memory dumps and limiting sc-memory threads

docs/changelog.md, sc-memory/sc-memory/sc_type.cpp, sc-memory/sc-memory/sc_type.hpp, sc-memory/sc-memory/scs/scs.g4, sc-memory/sc-memory/scs/scs_parser.cpp, sc-memory/sc-memory/scs/scs_parser.hpp, sc-memory/tests/scs/units/test_scs_common.cpp, sc-memory/tests/scs/units/test_scs_level_1.cpp, sc-memory/tests/scs/units/test_scs_utils.hpp, scripts/kb-scripts/support_scripts/scs_writer.py
=> [memory][scs][gwf] Allow to assign links to its system identifiers; fix resolve sc.g-links with the same system identifier

sc-memory/sc-core/sc_memory_context_manager.c, sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-action/sc_memory_create_elements_by_scs_json_action.hpp, sc-tools/sc-server/src/sc-server-impl/sc_server.cpp, sc-tools/sc-server/src/sc-server-impl/sc_server.hpp, sc-tools/sc-server/src/sc-server-impl/sc_server_impl.cpp, sc-tools/sc-server/src/sc-server-impl/sc_server_impl.hpp, sc-tools/sc-server/tests/api/units/sc_server_test.hpp, sc-tools/sc-server/tests/api/units/test_connection.cpp
=> [tools][server] Check session before emit action by it

sc-memory/sc-memory/sc_event.cpp
=> [memory][events] Fix users providing in events emission

docs/changelog.md, sc-memory/sc-core/sc-store/sc_event.c, sc-memory/sc-core/sc_memory.c, sc-memory/sc-core/sc_memory.h, sc-memory/sc-core/sc_memory_context_manager.c, sc-memory/sc-core/sc_memory_context_manager.h, sc-memory/sc-core/sc_memory_context_permissions.h, sc-memory/sc-memory/sc_memory.cpp, sc-memory/sc-memory/sc_memory.hpp, sc-memory/tests/sc-memory/events/test_sc_event.cpp
=> [memory][context] Block events mode

docs/changelog.md, sc-memory/sc-core/sc-store/sc-fs-memory/sc_dictionary_fs_memory_private.c
=> [memory][fs-memory] Use reenterable strtok

sc-memory/sc-core/sc_memory.c, sc-memory/sc-core/sc_memory.h, sc-memory/sc-memory/sc_memory.cpp, sc-memory/sc-memory/sc_memory.hpp
=> [memory] Fix cpp system context and c system context initialize order

docs/scs/sc_element_types.md
=> [docs] Fix type for sc_node_class

sc-kpm/sc-agents-common/sc_agents_common.cpp, sc-kpm/sc-search/search.c, sc-kpm/sc-ui/ui.cpp, sc-kpm/sc-utils/utils.c
=> [kpm] Set system context for modules initialize

docs/changelog.md, sc-memory/sc-memory/sc_struct.cpp, sc-memory/sc-memory/sc_template.cpp, sc-memory/sc-memory/sc_template.hpp, sc-memory/sc-memory/sc_template_build.cpp, sc-memory/sc-memory/sc_template_gen.cpp, sc-memory/sc-memory/sc_template_scs.cpp, sc-memory/sc-memory/sc_template_search.cpp, sc-memory/sc-memory/sc_type.hpp, sc-memory/tests/sc-memory/common/test_sc_struct.cpp, sc-memory/tests/sc-memory/common/test_sc_type.cpp, sc-memory/tests/sc-memory/templates/test_sc_templates_common.cpp, sc-memory/tests/sc-memory/templates/test_sc_templates_gen_api.cpp, sc-memory/tests/sc-memory/templates/test_sc_templates_scs.cpp, sc-memory/tests/sc-memory/templates/test_sc_templates_search_api.cpp, sc-memory/tests/sc-memory/templates/test_sc_templates_struct.cpp, sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-action/sc_memory_make_template_json_action.hpp
=> [memory][template][build][gen][search] Replacement for edges in sc-templates

CMakeLists.txt, docs/changelog.md, sc-memory/sc-core/sc-store/sc_element.h, sc-memory/sc-core/sc-store/sc_iterator3.c, sc-memory/sc-core/sc-store/sc_storage.c
=> [memory][cmake] Compile option for optimize checking local user permissions

docs/changelog.md, sc-memory/sc-core/sc-store/sc_iterator3.c, sc-memory/tests/sc-memory/common/test_sc_elements.cpp
=> [memory][core] Fix erasing sc-connectors during iterating

sc-memory/sc-core/sc-store/sc-container/sc-hash-table/sc_hash_table.h, sc-memory/sc-core/sc_keynodes.c, sc-memory/sc-core/sc_keynodes.h, sc-memory/sc-core/sc_memory_context_manager.c, sc-memory/sc-core/sc_memory_context_permissions.c, sc-memory/sc-core/sc_memory_context_permissions.h, sc-memory/sc-core/sc_memory_context_private.h, sc-memory/tests/sc-memory/common/test_sc_memory_context.cpp, sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-action/sc_memory_connection_info_json_action.hpp, sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-action/sc_memory_json_action_defines.hpp, sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-action/sc_memory_json_actions_handler.cpp
=> [memory][context] Implement permission handlers for users dynamically added to and removed from sets

CMakeLists.txt, docs/changelog.md, sc-memory/sc-core/sc-store/sc-base/sc_allocator.h, sc-memory/sc-core/sc-store/sc-base/sc_monitor.c, sc-memory/sc-core/sc-store/sc-base/sc_monitor.h, sc-memory/sc-core/sc-store/sc-base/sc_monitor_table.c, sc-memory/sc-core/sc-store/sc-base/sc_monitor_table.h, sc-memory/sc-core/sc-store/sc-container/sc-queue/sc_queue.c, sc-memory/sc-core/sc-store/sc-container/sc-queue/sc_queue.h, sc-memory/sc-core/sc-store/sc-event/sc_event_queue.c, sc-memory/sc-core/sc-store/sc-event/sc_event_queue.h, sc-memory/sc-core/sc-store/sc-fs-memory/sc_dictionary_fs_memory.c, sc-memory/sc-core/sc-store/sc-fs-memory/sc_dictionary_fs_memory_private.h, sc-memory/sc-core/sc-store/sc_event.c, sc-memory/sc-core/sc-store/sc_iterator3.c, sc-memory/sc-core/sc-store/sc_storage.c, sc-memory/sc-core/sc-store/sc_storage_private.h, sc-memory/sc-core/sc_memory_context_permissions.h
=> [memory][base][monitor][queue] Implement array-based queue, optimize dynamic memory usage; clean monitor tables by size threshold

docs/changelog.md, sc-memory/sc-core/sc-store/sc-base/sc_monitor_table.c, sc-memory/sc-core/sc-store/sc-container/sc-string/sc_string.h, sc-memory/sc-core/sc-store/sc-fs-memory/sc_dictionary_fs_memory.c, sc-memory/sc-core/sc-store/sc_storage.c, sc-memory/sc-core/sc-store/sc_storage_dump_manager.c, sc-memory/sc-core/sc-store/sc_types.h, sc-memory/sc-core/sc_helper.c, sc-memory/sc-core/sc_memory.c, sc-memory/sc-core/sc_memory_context_permissions.c, sc-memory/sc-memory/sc_addr.hpp, sc-memory/sc-memory/sc_template_search.cpp, sc-memory/sc-memory/sc_utils.hpp, sc-memory/tests/sc-memory/common/test_sc_elements.cpp, sc-memory/tests/sc-memory/common/test_sc_memory_core.cpp, sc-memory/tests/sc-memory/containers/test_sc_dictionary.cpp, sc-memory/tests/sc-memory/fs-storage/test_sc_dictionary_fs_memory_api.cpp, sc-memory/tests/sc-memory/templates/test_sc_templates_common.cpp, sc-tools/codegen/Parser/LanguageTypes/Class.cpp, sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-action/sc_memory_check_elements_json_action.hpp, sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-action/sc_memory_delete_elements_json_action.hpp
=> [memory][core] Platform-independent literal types; unify sc_addr_hash using; ScAddrHashFunc without template argument

docs/changelog.md, sc-memory/sc-memory/CMakeLists.txt, sc-memory/sc-memory/sc_iterator.cpp, sc-memory/sc-memory/sc_iterator.hpp, sc-memory/sc-memory/sc_iterator.tpp, sc-memory/sc-memory/sc_memory.hpp, sc-memory/sc-memory/sc_type.hpp
This is to avoid implementing specializations for new classes inherited from ScAddr and ScType every time.
=> [memory][iterator] Fix duplication of iterator specializations

docs/changelog.md, sc-memory/sc-memory/sc_addr.hpp, sc-memory/sc-memory/sc_template.cpp, sc-memory/sc-memory/sc_template.hpp, sc-memory/sc-memory/sc_template_gen.cpp, sc-memory/sc-memory/sc_template_private.hpp, sc-memory/sc-memory/sc_template_scs.cpp, sc-memory/sc-memory/sc_template_search.cpp
=> [memory][template] Separate template definition and implementation

CMakeLists.txt
=> [cmake] Fix compile flag for optimization searching input connectors

sc-memory/sc-core/sc-store/sc_storage.c
=> [memory][monitor] Use actual number of monitors

sc-kpm/sc-search/search_utils.c
=> fix: change node type

docs/changelog.md, sc-memory/sc-core/sc-store/sc-fs-memory/sc_dictionary_fs_memory.c, sc-memory/sc-core/sc-store/sc-fs-memory/sc_dictionary_fs_memory.h, sc-memory/sc-core/sc-store/sc-fs-memory/sc_dictionary_fs_memory_private.h
=> [memory][fs-memory] Resolve string in all channels

docs/changelog.md, sc-memory/sc-memory/sc_addr.hpp, sc-memory/tests/sc-memory/common/test_sc_addr.cpp
=> [memory][addr] unordered_map with ScAddr as key

docs/changelog.md, docs/sc-memory/api/cpp/core/api.md, docs/sc-memory/api/cpp/extended/template_api.md, sc-memory/sc-memory/sc_memory.cpp, sc-memory/sc-memory/sc_memory.hpp, sc-memory/sc-memory/sc_template.hpp, sc-memory/sc-memory/sc_template_build.cpp, sc-memory/sc-memory/sc_template_load.cpp, sc-memory/sc-memory/sc_template_scs.cpp, sc-memory/tests/sc-memory/scs/test_scs_helper.cpp, sc-memory/tests/sc-memory/templates/test_sc_templates_load.cpp, sc-memory/tests/sc-memory/templates/test_sc_templates_scs.cpp, sc-tools/codegen/Parser/LanguageTypes/Class.cpp, sc-tools/sc-server/src/sc-server-impl/sc_server_defines.hpp
=> [memory][template] Implement load program object of sc-template into sc-memory

sc-memory/sc-memory/sc_module.tpp, sc-memory/tests/sc-memory/agents/test_sc_agents.cpp
=> [memory][module][tests] Fix subscription of ScActionInitiatedAgent with module

sc-memory/sc-memory/sc_agent_builder.tpp, sc-memory/sc-memory/sc_keynodes.hpp, sc-memory/tests/sc-memory/agents/test_sc_specified_agents.cpp, sc-memory/tests/sc-memory/common/test_sc_keynodes.cpp
Special feature for agent of interpretation scp-agents
=> [memory][agents] Support platform independent agents

docs/sc-memory/api/cpp/extended/agents/agent_context.md, sc-memory/sc-memory/sc_agent_context.hpp, sc-memory/sc-memory/sc_agent_context.tpp, sc-memory/sc-memory/sc_agent_manager.hpp, sc-memory/sc-memory/sc_agent_manager.tpp, sc-memory/sc-memory/sc_module.tpp, sc-memory/tests/sc-memory/agents/test_sc_agents.cpp, sc-memory/tests/sc-memory/agents/test_sc_specified_agents.cpp
This feature will be useful for agents of interpretation of scp-agents.
=> [memory][agent][manager] Allow to subscribe agent class with several agent implementations

docs/sc-memory/api/cpp/extended/agents/waiters.md
=> [docs] Fix GenerateConditionWaiter call

README.md
=> [docs] Use correct links in readme

docs/changelog.md
=> Fix BuildTemplate deprecation

docs/changelog.md, docs/sc-memory/api/cpp/extended/agents/actions.md, docs/sc-memory/api/cpp/extended/agents/images/actions/action_initiated_with_waiting.gwf, sc-memory/sc-memory/sc_action.cpp, sc-memory/sc-memory/sc_action.hpp, sc-memory/sc-memory/sc_keynodes.hpp, sc-memory/tests/sc-memory/agents/test_sc_action.cpp, sc-memory/tests/sc-memory/common/test_sc_keynodes.cpp
=> Store wait time in kb

sc-memory/sc-memory/sc_memory.hpp
=> [memory] Use correct deprecation messages

sc-tools/sc-builder/include/sc-builder/scs_loader.hpp
=> Remove unused include

sc-kpm/sc-common/include/sc-common/sc_defines.h, sc-kpm/sc-common/src/sc_keynodes.c, sc-kpm/sc-search/src/search_keynodes.c, sc-kpm/sc-search/src/search_keynodes.h, sc-kpm/sc-utils/src/utils_keynodes.h, sc-kpm/sc-utils/tests/units/sc-utils.cpp
=> [kpm][fix] sc-search keynodes duplicate sc-common keynodes

docs/index.md, mkdocs.yml
=> Remove sc-server from docs

docs/build/config.md, docs/changelog.md, sc-memory/sc-core/include/sc-core/sc_memory.h, sc-memory/sc-core/include/sc-core/sc_memory_params.h, sc-memory/sc-core/src/sc-store/sc-fs-memory/sc_dictionary_fs_memory.c, sc-memory/sc-core/src/sc_memory.c, sc-memory/sc-core/src/sc_memory_ext.c, sc-memory/sc-core/src/sc_memory_ext.h, sc-memory/sc-core/src/sc_memory_params.c, sc-tools/sc-config/include/sc-config/sc_config.hpp, sc-tools/sc-config/include/sc-config/sc_memory_config.hpp, sc-tools/sc-config/src/sc_config.cpp, sc-tools/sc-config/src/sc_memory_config.cpp, sc-tools/sc-config/tests/empty-multiextensions.ini, sc-tools/sc-config/tests/multiextensions-with-spaces.ini, sc-tools/sc-config/tests/multiextensions.ini, sc-tools/sc-config/tests/not-normalized-multiextensions.ini, sc-tools/sc-config/tests/units/test_config.cpp
Dependencies:
- https://github.com/ostis-ai/sc-machine/pull/429
I will add tests after https://github.com/ostis-ai/sc-machine/pull/429 merge, locally everything works fine
=> [tools][config][extensions] Allow multiple extension directories for sc-memory

sc-memory/sc-memory/include/sc-memory/_template/sc_agent_builder.tpp, sc-memory/sc-memory/src/sc_template_gen.cpp
Clarifies prints for sc-types in error messages.
=> [refactor][memory] Use pretty prints for sc-types in exception messages

sc-memory/sc-memory/include/sc-memory/sc_utils.hpp, sc-memory/sc-memory/src/sc_utils.cpp, sc-memory/sc-memory/tests/sc-memory/units/common/test_sc_utils.cpp
Fixes repo.path parsing for launching command ./sc-machine/bin/sc-builder -i repo.path -o kb.bin --clear
=> [memory][string][utils] Fix getting file extension for file without path

docs/sc-memory/api/cpp/core/api.md
=> [docs] Fix typos

README.md, docs/index.md, docs/quick_start.md, mkdocs.yml
I've made some updates to our docs which I think will make the installation process easier to understand to newcomers.
Started from a discussion on #406
=> [docs] Add Quick Start page

README.md
=> [docs][fix] Tests badges in readme

sc-tools/sc-builder/include/sc-builder/scs_loader.hpp
=> [tools][builder][loader] Add pragma once for SCsLoader

docs/build/build_system.md, docs/build/quick_start.md, docs/dev/codestyle.md, docs/index.md, docs/quick_start.md, docs/sc-memory/api/cpp/extended/agents/agent_context.md, docs/sc-memory/api/cpp/extended/agents/event_subscriptions.md, docs/sc-memory/api/cpp/extended/agents/events.md, docs/sc-memory/api/cpp/extended/helper_api.md, docs/sc-memory/api/cpp/extended/template_api.md, docs/sc-memory/api/cpp/guides/simple_guide_for_implementing_agent.md, docs/sc-tools/kb_repo_file.md, docs/sc-tools/migrate_to_new_agent_api.md, docs/sc-tools/sc_builder.md, docs/sc-tools/sc_machine.md, mkdocs.yml
=> [docs] Unify docs header namings

docs/build/build_system.md, docs/build/quick_start.md
=> [docs] Describe using Ninja generator for CMake

docs/changelog.md, sc-memory/sc-core/src/sc-store/sc_storage.c, sc-memory/sc-memory/tests/sc-memory/units/common/test_sc_iterator3.cpp
=> [memory][core][storage] Fix iterating sc-connectors with sc-edge loops

docs/changelog.md, docs/sc-memory/api/cpp/core/api.md, docs/sc-memory/api/cpp/extended/agents/agents.md, docs/sc-memory/api/cpp/guides/simple_guide_for_implementing_agent.md, sc-memory/sc-memory/CMakeLists.txt, sc-memory/sc-memory/include/sc-memory/_template/sc_agent.tpp, sc-memory/sc-memory/include/sc-memory/_template/sc_agent_manager.tpp, sc-memory/sc-memory/include/sc-memory/_template/utils/sc_log.tpp, sc-memory/sc-memory/include/sc-memory/sc_agent.hpp, sc-memory/sc-memory/include/sc-memory/sc_agent_manager.hpp, sc-memory/sc-memory/include/sc-memory/sc_debug.hpp, sc-memory/sc-memory/include/sc-memory/sc_keynodes.hpp, sc-memory/sc-memory/include/sc-memory/utils/sc_log.hpp, sc-memory/sc-memory/include/sc-memory/utils/sc_logger.hpp, sc-memory/sc-memory/include/sc-memory/utils/sc_message.hpp, sc-memory/sc-memory/src/sc_keynodes.cpp, sc-memory/sc-memory/src/sc_memory.cpp, sc-memory/sc-memory/src/utils/sc_log.cpp, sc-memory/sc-memory/src/utils/sc_logger.cpp, sc-memory/sc-memory/tests/sc-memory/units/agents/test_sc_agent.cpp, sc-memory/sc-memory/tests/sc-memory/units/agents/test_sc_agent.hpp, sc-memory/sc-memory/tests/sc-memory/units/agents/test_sc_agents.cpp, sc-memory/sc-memory/tests/sc-memory/units/common/test_sc_debug.cpp
This PR allows to create several loggers in the system.
=> [memory][utils][logger] Allow to create multiple loggers

docs/changelog.md, docs/index.md, docs/sc-memory/api/cpp/extended/images/permissions/erase_local_read_permissions_for_user.gwf, docs/sc-memory/api/cpp/extended/images/permissions/generate_local_read_permissions_for_user.gwf, docs/sc-memory/api/cpp/extended/images/permissions/global_read_permissions_for_user.gwf, docs/sc-memory/api/cpp/extended/images/permissions/global_read_permissions_for_users_set.gwf, docs/sc-memory/api/cpp/extended/images/permissions/local_read_permissions_for_user.gwf, docs/sc-memory/api/cpp/extended/images/permissions/local_read_permissions_for_users_set.gwf, docs/sc-memory/api/cpp/extended/images/permissions/no_global_read_permissions_for_user.gwf, docs/sc-memory/api/cpp/extended/images/permissions/no_global_read_permissions_for_users_set.gwf, docs/sc-memory/api/cpp/extended/images/permissions/no_local_read_permissions_for_user.gwf, docs/sc-memory/api/cpp/extended/images/permissions/no_local_read_permissions_for_users_set.gwf, docs/sc-memory/api/cpp/extended/permissions_api.md, mkdocs.yml, sc-memory/sc-core/src/sc_memory_context_permissions.c, sc-memory/sc-memory/include/sc-memory/sc_keynodes.hpp, sc-memory/sc-memory/tests/sc-memory/units/common/test_sc_keynodes.cpp, sc-memory/sc-memory/tests/sc-memory/units/common/test_sc_memory_context.cpp
I understood that for ease of handling permissions, it would be necessary to implement methods in the API to handle users and their permissions. I'll will do this after merge of the new C++ Agents API.
And I'm also mindful of the need to add implements of contexts to perform actions not in all kb, and its part. This is exactly what I will be doing now.
=> [memory][core][context][docs] Documentation for user permissions
